### ISSUE TITLE
Nomenclature for noise variables in NGSI-LD

### ISSUE THREAD

**Issue by DiEVeXx** [smart-data-models/data-models#15]
I am developing a service for the conversion of data reported by a number of devices including air quality and noise.

The information about the context of the data that I have is the following link: https://raw.githubusercontent.com/smart-data-models/data-models/master/context.jsonld

I have seen that in the NGSI-LD changes the names for certain gases such as CO, NO2, etc have been changed to lower case for NGSI-LD but I have not been able to find what is the correct nomenclature for the observed noise levels and since these in version 2 of NGSI-LD are written as "sonometerClass", "LAeq", "LAFmax", "LAFmin", "LASmax", "LASmin" what would be the correct way to name them? Will they be added soon? 

Thank you very much, best regards

**Comment by albertoabellagarcia** [comment]
As a general rule, all the properties in the initiative are written camelCase. See the [coding guidelines](https://smartdatamodels.org/index.php/coding-data-models/)
If you find missing properties you can do a pull request in the model to extend for those properties (but for these properties you mentioned it should be done in the [environment](https://github.com/smart-data-models/dataModel.Environment) repo where [noiseLevelObserved](https://github.com/smart-data-models/dataModel.Environment/tree/master/NoiseLevelObserved) is located
