### ISSUE TITLE
Broken example links 

### ISSUE THREAD

**Issue by dpatil-fw** [smart-data-models/data-models#23]
Here https://github.com/smart-data-models/data-models

In this paragraph:

/examples. This directory contains the examples for the different versions of NGSI standard and different formats. Example: schema.json of WeatherObserved - example.json: a JSON example file key values of NGSI v2 Example: example.json of WeatherObserved - example-normalized.json: An example file in NGSI v2 normalized format Example: example-normalized.json of WeatherObserved - example.jsonld: a JSON example file key values of NGSI LD Example: example.json of WeatherObserved

the links:
https://github.com/smart-data-models/dataModel.Weather/blob/master/WeatherObserved/example.json
https://github.com/smart-data-models/dataModel.Weather/blob/master/WeatherObserved/example-normalized.json
https://github.com/smart-data-models/dataModel.Weather/blob/master/WeatherObserved/example.jsonld

all above links are broken.

Should be:

https://github.com/smart-data-models/dataModel.Weather/blob/master/WeatherObserved/examples/example.json
https://github.com/smart-data-models/dataModel.Weather/blob/master/WeatherObserved/examples/example-normalized.json
https://github.com/smart-data-models/dataModel.Weather/blob/master/WeatherObserved/examples/example.jsonld

**Comment by albertoabellagarcia** [comment]
fixed.
thanks a lot.
