### ISSUE TITLE
Edit configuration files

### ISSUE THREAD

**Issue by jiuaige** [smart-data-models/data-models#26]
I have a question to ask the author, what editor do you use to edit the json and yaml configuration files, because it is easy to make mistakes if you modify the files directly

**Comment by jiuaige** [comment]
Can u give me some contacts skype or mail or twitter

**Comment by albertoabellagarcia** [comment]
For JSON and JSON schema Pycharm is a good option. For yaml files as well but all the YAML files in this initiative are created automatically therefore they do not need to be edited manually.
