### ISSUE TITLE
Which @context to use as reference?

### ISSUE THREAD

**Issue by Blobonat** [smart-data-models/data-models#35]
Which `@context` should be used as reference for the smart data models? The [@context](https://smart-data-models.github.io/data-models/context.jsonld) in this umbrella repo uses different URIs than the `@context`-files in the domain specific repositories (e.g. `https://uri.fiware.org/ns/data-models#refRoad` vs. `https://smartdatamodels.org/dataModel.Transportation/refRoad`). Also the `@context` in this repo hasn't been updated for 2 years and therefore does not include all attributes from the current versions of the data models. On the other hand the `@context`-files in the domain specific repositories do include URIs only for attributes and not for the entity types themself (e.g. `Road`, `RoadSegment`).

In haven't found any recommendation in the modeling guidelines. What is the best practice regarding the URIs for using the smart data models (without mapping the models to external ontologies)?

**Comment by albertoabellagarcia** [comment]
You are correct that better documentation should be made available. The @context of the umbrella repo is there for compatibility reasons with old versions.

1) Our aim is not to create the canonical URL for the concepts. There are plenty of ontologies around there. We also know that most of our users are using linked data versions of the tools, therefore we also provide long IRI for the attributes. They are the root of every subject in a file named context.jsonld  (see this [example](https://github.com/smart-data-models/dataModel.Aeronautics/blob/master/context.jsonld)). All of the first-level attributes should have an IRI like the one you mention, taking you to a basic info page of the term.

2) Having said 1) we provide a service for different mapping subjects into a single @context. It is available on the main page Home -> Tools -> [Subjects' @context merger] (https://smartdatamodels.org/index.php/generate-a-local-context-based-on-smart-data-models-iris/)

3) Additionally if you want to map them with external ontologies you can use this service available at the front page Home -> Tools -> [Mapper  @context with external ontologies] (https://smartdatamodels.org/index.php/generate-acontext-based-on-external-ontologies-iris/)

Regarding a recommendation without mapping external ontologies. Use the @context of every subject (group of data models)
