### ISSUE TITLE
How to automatically generate the model.yaml and swagger.yaml

### ISSUE THREAD

**Issue by dzgrief** [smart-data-models/data-models#36]
Is there any tool or script that can automatically generate model.yaml file from schema.json?

Is the swagger.yaml file automatically generated from model.yaml and schema.json？

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/7501701/185053622-1c22e1e8-7014-43cc-b5a2-26291c1a96a5.png">

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/7501701/185053680-60cbe778-2931-4738-8ed4-5277c5c0ff33.png">

**Comment by albertoabellagarcia** [comment]
yes we have couple of scriptsfor the creation of the model.yaml and for the swagger.yaml.

**Comment by albertoabellagarcia** [comment]
you have now published the scripts (they are not meant for sharing the code, so they are not properly documented). 
in this folder [https://github.com/smart-data-models/data-models/tree/master/utils](https://github.com/smart-data-models/data-models/tree/master/utils) you have the script starting with 10 for the model generation and the one starting by 50 of the swagger generation. Additionally you have a version for the creation of the documentation (the one starting with 20)

**Comment by albertoabellagarcia** [comment]
I'll be glad to know more what you need please send me an email at info@smartdatamodels.org
