### ISSUE TITLE
Install of PYSMARTDATAMODEL fails using poetry

### ISSUE THREAD

**Issue by auphofBSF** [smart-data-models/data-models#37]
In attempting to install `pysmartdatamodel` it fails with errors regarding dependencies

# Expected behaviour:
I should be able to add `pysmartdatamodels `  as a dependency to my application 
`poetry add   --editable git+https://github.com/smart-data-models/data-models.git#subdirectory=pysmartdatamodels`
and use  it with the following
```
from pysmartdatamodels import list_all_datamodels
print(list_all_datamodels())
```

# Actual Behaviour
`poetry add .....` results in the following error
```
Because pysmartdatamodels (0.2.3) @ git+https://github.com/smart-data-models/data-models.git@HEAD#subdirectory=pysmartdatamodels depends on sys (*) which doesn't match any versions, pysmartdatamodels is forbidden.
So, because module-sll-smartdatamodels-22q3 depends on pysmartdatamodels (0.2.3) @ git+https://github.com/smart-data-models/data-models.git#subdirectory=pysmartdatamodels, version solving failed.
```

# Steps to reproduce the behavior
My Environment is Python 3,9, Python 3.10 and using poetry (1.2.1) as dependency and virtualenv manger 
installation command  is `poetry add   --editable git+https://github.com/smart-data-models/data-models.git#subdirectory=pysmartdatamodels`

working example of this can be found at 
GIST https://gist.github.com/auphofBSF/abffe6f37bfbc5077eedf10304988157

# Analysis
the `INSTALL_REQUIRES`  in `setup.py`  lists as dependencies some python core builtin dependencies.  `INSTALL_REQUIRES` is not meant to be the main source of requirements and is only meant to show external requirements.   
Python dependency management  has undergone a lot of change with PEP517,518 and 621 I will add a separate PR to help in this manner, but 1st I will issue a PR that fixes this immediate situation in `setup.py`.

**Comment by auphofBSF** [comment]
as mentioned above a separate PR #39 created for proposals and example of enhancements to `pysmartdatamodels`

**Comment by SLLau** [comment]
Tested accepted PRs #38,#39  and working great from branch master, 

Thank you for accepting PRs @albertoabellagarcia @wistefan 
I believe issue can be marked as resolved

**Comment by auphofBSF** [comment]
👍👍
