### ISSUE TITLE
SAREF terms have outdated URIs

### ISSUE THREAD

**Issue by a39172** [smart-data-models/data-models#42]
I think the file [saref-terms.yaml](https://github.com/smart-data-models/data-models/blob/master/saref-terms.yaml) has outdated (not working) URIs; for example, shouldn't the URI https://w3id.org/saref#temperature be replaced with https://saref.etsi.org/core/Temperature?

**Comment by albertoabellagarcia** [comment]
In fact this file is useless, removed.

thanks
