### ISSUE TITLE
Full context update?

### ISSUE THREAD

**Issue by ScorpioBroker** [smart-data-models/data-models#54]
Hi,

in the sub repos for the data models some of the full URIs have been updated to e.g.
https://smartdatamodels.org/dataModel.Environment/AirQualityObserved 
and this is also reflected in the submodels specific at context 
https://github.com/smart-data-models/dataModel.Environment/blob/master/context.jsonld
however the full context provided 
here 
https://raw.githubusercontent.com/smart-data-models/data-models/master/context.jsonld
or here 
https://smart-data-models.github.io/data-models/context.jsonld

still have the the older URI 
https://uri.fiware.org/ns/data-models#AirQualityObserved

so the full context is incompatible with the updated subcontexts.

Will the full context be updated?

Thanks

**Comment by albertoabellagarcia** [comment]
You are right, this context https://raw.githubusercontent.com/smart-data-models/data-models/master/context.jsonld is an obsolete copy, and it should not be used. It is kept for old implementations.
In case you need a context merging several subjects (eventually all of them) you can use this service on the front page of the smartdatamodels.org site [https://smartdatamodels.org/index.php/generate-a-local-context-based-on-smart-data-models-iris/](https://smartdatamodels.org/index.php/generate-a-local-context-based-on-smart-data-models-iris/) located at home -> toos-> Subjects' @context merger
thanks
