### ISSUE TITLE
Missing dependency `ruamel.yaml`

### ISSUE THREAD

**Issue by FlorianK13** [smart-data-models/data-models#59]
# Concerning the python package pysmartdatamodels

It seems like the dependency ruamel.yaml is not part of the pyproject.toml file. I would have created a PR, but the pyproject.toml file is also not part of the repository anymore (maybe deleted by mistake?)

## Reproduce the error
1. Run `pip install pysmartdatamodels`
2. Run `from pysmartdatamodels import pysmartdatamodels as sdm`
3. Get the error: ModuleNotFoundError: No module named 'ruamel'

**Comment by albertoabellagarcia** [comment]
it could be our error certainly. 
Checking...
you're right, we need to update the version
Thanks
