### ISSUE TITLE
Missing howto.md and broken link in guidelines.md

### ISSUE THREAD

**Issue by danvilmot** [smart-data-models/data-models#6]
In the guidelines.md, the https://github.com/smart-data-models/data-models/blob/master/guidelines.md#data-models-guidelines has a broken link to the file [howto.md](https://github.com/smart-data-models/data-models/blob/master/howto.md).
As I can see, most of the topics of the https://github.com/FIWARE/data-models/blob/master/specs/howto.md are covered in the guidelines.md but some interesting pieces of documentation as [Going through a Data Model](https://github.com/FIWARE/data-models/blob/master/specs/howto.md#going-through-a-data-model) is missing. I suggest maintaining it so I see three options:

a. To include the "Going through a Data Model" topic in the guidelines.md where include both v2 and NGSI-LD. And delete de reference to the howto.md
b. To create a new document "goingthroughadatamodel.md" with this piece of documentation and a future example for NGSI-LD.
c. Not to include this piece of documentation and delete the reference to the howto.md

I could solve this issue if you tell me what should be organization of this documentation.

**Comment by albertoabellagarcia** [comment]
1) fixed the link
2) solution a
