### ISSUE TITLE
Converting JSON-LD Smart Data Models to RDF/Turtle File Ontology

### ISSUE THREAD

**Issue by Max-Bld** [smart-data-models/data-models#61]
Hello,

I am trying to experiment with *Smart Data Models* in order to add a common semantic layer to multiple heterogeneous data sources. 

For this purpose, I would like to translate the JSON-LD file to a .ttl (RDF serialization) file ontology in order to explore and manipulate it in Protégé Software with the following steps:
- Choose the model I need [Smart Destination, TourismDestinations](https://github.com/smart-data-models/dataModel.TourismDestinations/tree/abfd461470b64ffec5dc4ba862f3dd0a925a4039)
- Merge the [context.jsonld](https://github.com/smart-data-models/dataModel.TourismDestinations/blob/abfd461470b64ffec5dc4ba862f3dd0a925a4039/context.jsonld) file and [schemaDTLD.json](schemaDTDL.json) file in a single one enclosed here: [sdm_merged_file.json](https://github.com/user-attachments/files/15835726/sdm_merged_file.json)
- Translate from JSON-LD to .ttl in [easyrdf.org](https://www.easyrdf.org/converter)

The output from easy-rdf is not satisfactory because the **contents** field is missing, while I was expecting to have a list of classes:
```turtle
@prefix dc: <http://purl.org/dc/terms/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<dtmi:com:ngsi-ld:TouristProfile;0>
  a <http://njh.me/Interface> ;
  dc:description "Description of a tourist profile based on the characteristics of a person, trip, choice of stay and spending while in destination."^^xsd:string .
```

Next, I tried to tweak it by adding a **contents** line to the context part of the merged json-ld file:
```json
{
    "@context": {
        "1": "https://smartdatamodels.org/dataModel.TourismDestinations/1",

        [...]

        "wheelChairAccessible": "https://smartdatamodels.org/dataModel.TourismDestinations/wheelChairAccessible",
        "contents": "https://smartdatamodels.org/example"
    },

        [...]
```

But the result is not satisfactory neither, I have a bunch of blank nodes instead of well defined class:
```turtle
@prefix dc: <http://purl.org/dc/terms/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix ns0: <https://smartdatamodels.org/> .

<dtmi:com:ngsi-ld:TouristProfile;0>
  a <http://njh.me/Interface> ;
  dc:description "Description of a tourist profile based on the characteristics of a person, trip, choice of stay and spending while in destination."^^xsd:string ;
  ns0:example [
    a <http://njh.me/Property> ;
    ns0:name "alternateName"^^xsd:string

[...]

[
    a <http://njh.me/Telemetry> ;
    ns0:name "travelPartyComposition"^^xsd:string
  ] .
```

Does what I want to do have any sense? Is there a way to translate an SDM to a turtle ontology?

**Comment by albertoabellagarcia** [comment]
We are currently in progress to create such tool, but unfortunately we cannot commit on a date because it depends on variable resources but we will be glad to collaborate about it. 
use our [support](https://smartdatamodels.org/index.php/support/) or [live support](https://calendly.com/smartdatamodels)

**Comment by albertoabellagarcia** [comment]
BTW the schemaDTDL.json makes no sense to merge it as long as it is a DTDL(a microsoft digital twins solution).

**Comment by Max-Bld** [comment]
Thank you for the clarifications!
