### ISSUE TITLE
Replace fuzzywuzzy by rapidfuzz

### ISSUE THREAD

**Issue by infomehdi** [smart-data-models/data-models#62]
`pysmartdatamodels` depends on `fuzzywuzzy` to enable the fuzzy search. This [libary](https://github.com/seatgeek/fuzzywuzzy):
- has been renamed and moved to [thefuzz](https://github.com/seatgeek/thefuzz)
- forces you to adopt the GPL license (instead of MIT)
- has a (better) alternative ([RapidFuzz](https://github.com/rapidfuzz/RapidFuzz))

Would you please change the dependency so that `pysmartdatamodels` uses `thefuzz` or directly `rapidfuzz` instead of `fuzzywuzzy`.

I would be happy to submit a PR, but I can not find the file where to change de the dependency, I can only find where the libary is [imported](https://github.com/smart-data-models/data-models/blob/master/pysmartdatamodels/pysmartdatamodels.py#L1255) (`from fuzzywuzzy import fuzz`)

**Comment by albertoabellagarcia** [comment]
we will be glad to have your PR on this [file](https://github.com/smart-data-models/data-models/blob/master/pysmartdatamodels/pysmartdatamodels.py)
