### ISSUE TITLE
Non usable JSON schemas in validator

### ISSUE THREAD

**Issue by EliottPaillard** [smart-data-models/data-models#65]
Hey @albertoabellagarcia,

You updated the smart data models few weeks ago (cf. https://github.com/smart-data-models/dataModel.Environment/issues/23)
Thank you for this.
However, you need also to update the schemas that are referenced in them.
It still may be not enough but you should also update the json schemas from https://github.com/smart-data-models/data-models

**Comment by albertoabellagarcia** [comment]
updated  the common here. There are other shared files bu we are going to update them as well.
