### ISSUE TITLE
import line confusing

### ISSUE THREAD

**Issue by marvkos** [smart-data-models/data-models#67]
Hello,

i tried to follow the README.md example code, but it produces the following error:
```sh
AttributeError: module 'pysmartdatamodels' has no attribute 'list_all_datamodels'
```

This is because the import line is wrong?

https://github.com/smart-data-models/data-models/blob/00223512a73f359135567513aa36c24c3daf5270/pysmartdatamodels/README.md?plain=1#L34

Isn't this correct:
```python
from pysmartdatamodels import pysmartdatamodels as sdm
```

**Comment by albertoabellagarcia** [comment]
absolutely

**Comment by albertoabellagarcia** [comment]
That is absolutely wrong but we need to create a new version of the package top fix it.
